all:
  vars:
    ansible_user: vagrant
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

prod:
  hosts:
    client:
      ansible_host: 192.168.99.11
  vars:
    ansible_password: vagrant
    env: production
